nginx_cmd = "/usr/local/bin/nginx"  #Nginx命令的全路径
nacos_addr = "127.0.0.1:8848" #nacos 服务地址
nacos_namespace = "4b139047-5e5c-4c57-8019-5db186785ab7"
nacos_group = "test"
reload_interval = 1000  # 刷新间隔

[atomgit-api]
nginx_config = "/usr/local/etc/nginx/servers/test-api.conf"  #Nginx config 配置
nginx_upstream = "test-api"     #upstream 名称
nacos_service_name = "test-api"   #nacos 服务名